apiVersion: v1
kind: Pod
metadata:
  labels:
    run: vulnerable-app
  name: vulnerable-app
spec:
  restartPolicy: Never
  containers:
  # Step 1: this version is based on 2.14.1 and is vulnerable to both ldap attack and DoS
  #- image: docker.io/asksven/l4-poc:2-14-1-1 
  # Step 2: this version is based on 2.16.0 and is neither vulnerable to ldap attack nor DoS
  #- image: docker.io/asksven/l4-poc:2-16-0-1
  # Step 3: this version is based on 2.16.0 and is not vulnerable to ldap but to DoS (based on another repo)
  #- image: docker.io/asksven/l4-poc:2-16-0-2
  # Step 5: this version is based on 2.17.0 and has JNDILookup removed. It is not vulnerable to ldap attack nor DoS, even with a "bad" PatternLayout
  #- image: docker.io/asksven/l4-poc:2-17-0-1
  # Step 6: same as step 5 but for the other repo
  #- image: docker.io/asksven/l4-poc:2-17-0-2
    imagePullPolicy: Always
    name: vulnerable-app
    ports:
    - containerPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: vulnerable-app
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: attacker
  name: attacker
spec:
  containers:
  - env:
    - name: LDAP_PORT
      value: "1389"
    - name: HTTP_PORT
      value: "80"
    image: edenfed/jndiexploit
    imagePullPolicy: Always
    name: attacker
---
apiVersion: v1
kind: Service
metadata:
  name: attacker
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: ldap
    port: 1389
    protocol: TCP
    targetPort: 1389
  selector:
    run: attacker
  type: ClusterIP